In [22]:
%load_ext autoreload
%autoreload 2

import llops as yp
import torch

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [15]:
torch.argmax(q, dim=1)

tensor([5, 0, 5, 1, 3, 8, 6, 2, 9, 0])

In [18]:
q = yp.rand((10,10), backend='torch', dtype='float32')
yp.argmin(q)

tensor(80)

In [21]:
print(q.transpose(-1,0))
print(q)

tensor([[0.4011, 0.2577, 0.4640, 0.7352, 0.6586, 0.1390, 0.7052, 0.5657, 0.0001,
         0.9537],
        [0.0748, 0.7208, 0.1957, 0.0973, 0.3704, 0.4656, 0.3475, 0.9610, 0.6662,
         0.0897],
        [0.2841, 0.9095, 0.7088, 0.7494, 0.6894, 0.5536, 0.3102, 0.0100, 0.0362,
         0.0107],
        [0.6485, 0.4799, 0.1844, 0.6970, 0.4505, 0.7456, 0.6142, 0.3773, 0.1804,
         0.5487],
        [0.5553, 0.7234, 0.4875, 0.4413, 0.3122, 0.7062, 0.2399, 0.8506, 0.8856,
         0.8199],
        [0.7650, 0.7566, 0.2588, 0.3636, 0.4177, 0.7355, 0.5272, 0.1048, 0.0212,
         0.1357],
        [0.3896, 0.6275, 0.3378, 0.4627, 0.1211, 0.1604, 0.8281, 0.8688, 0.9954,
         0.1339],
        [0.5401, 0.6361, 0.0324, 0.6292, 0.6517, 0.4286, 0.6559, 0.2049, 0.6067,
         0.8211],
        [0.1842, 0.4254, 0.9095, 0.1150, 0.3586, 0.4544, 0.2598, 0.8823, 0.4973,
         0.9878],
        [0.0138, 0.5898, 0.9062, 0.1403, 0.6208, 0.3324, 0.2244, 0.7773, 0.6138,
         0.1952]])
tensor([[

In [2]:
torch.ones((10,10))

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
torch.un

In [ ]:
bool_	Boolean (True or False) stored as a byte
int_	Default integer type (same as C long; normally either int64 or int32)
intc	Identical to C int (normally int32 or int64)
intp	Integer used for indexing (same as C ssize_t; normally either int32 or int64)
int8	Byte (-128 to 127)
int16	Integer (-32768 to 32767)
int32	Integer (-2147483648 to 2147483647)
int64	Integer (-9223372036854775808 to 9223372036854775807)
uint8	Unsigned integer (0 to 255)
uint16	Unsigned integer (0 to 65535)
uint32	Unsigned integer (0 to 4294967295)
uint64	Unsigned integer (0 to 18446744073709551615)
float_	Shorthand for float64.
float16	Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
float32	Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
float64	Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
complex_	Shorthand for complex128.
complex64	Complex number, represented by two 32-bit floats
complex128	Complex number, represented by two 64-bit floats

In [ ]:
import torch

In [ ]:
import nump